# Generated by Django 4.0.4 on 2022-08-06 13:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('father_name', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=20, null=True)),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=20)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo')),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('_face_features', models.JSONField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_classroom', to='manager.classroom')),
                ('user', models.ForeignKey(limit_choices_to={'account_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(choices=[('Term1', '1'), ('Term2', '2')], max_length=20)),
                ('exam_name', models.CharField(max_length=100)),
                ('mark', models.IntegerField()),
                ('fullmark', models.IntegerField()),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_mark', to='manager.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mark', to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mark', to='student.subject')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('pdf_from_teacher', models.FileField(blank=True, null=True, upload_to='pdf_teacher/')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_homeworkteacher', to='manager.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_homeworkteacher', to='student.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'user__account_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_homeworkteacher', to='manager.profile')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWorkStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('pdf_from_student', models.FileField(blank=True, null=True, upload_to='pdf_student/')),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_homework', to='student.homeworkteacher')),
                ('student', models.ForeignKey(limit_choices_to={'user__account_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_homework', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='DailyLessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('sunday', '1'), ('monday', '2'), ('tuesday', '3'), ('wensday', '4'), ('thursday', '5')], max_length=30)),
                ('period', models.CharField(choices=[('first', '1'), ('second', '2'), ('third', '3'), ('fourth', '4'), ('fifth', '5'), ('sixth', '6'), ('seventh', '7')], max_length=30)),
                ('className', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'user__account_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_daelylessons', to='manager.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
                ('attendance_status', models.CharField(choices=[(1, 'present'), (2, 'leave'), (3, 'absent')], default='absent', max_length=10)),
                ('student', models.ForeignKey(limit_choices_to={'user__account_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True)),
                ('star', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='manager.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('star', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('condition', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.subject')),
            ],
        ),
    ]
