# Generated by Django 4.0.4 on 2022-05-23 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_post_date_post_timee'),
        ('student', '0002_rename_subject_name_subject_subject_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='classroom',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='classroom_mark', to='manager.classroom'),
            preserve_default=False,
        ),
    ]
