# Generated by Django 4.0.4 on 2022-06-10 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_dailylessons_teacher_alter_dailylessons_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkstudent',
            name='student',
            field=models.ForeignKey(limit_choices_to={'user__account_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_homework', to='student.student'),
        ),
    ]
