# Generated by Django 4.0.4 on 2022-06-11 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_holiday_head_teacher'),
        ('student', '0007_alter_dailylessons_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylessons',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user__account_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_daelylessons', to='manager.profile'),
        ),
    ]
