# Generated by Django 4.0.4 on 2022-07-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_dailylessons_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='_face_features',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
