# Generated by Django 4.0.4 on 2022-07-21 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_student__face_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now_add=True)),
                ('attendance_status', models.CharField(choices=[(1, 'present'), (2, 'leave'), (3, 'absent')], default='absent', max_length=10)),
                ('student', models.ForeignKey(limit_choices_to={'user__account_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='student.student')),
            ],
        ),
    ]
