# Generated by Django 4.0.4 on 2022-07-24 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_rename_title_profile_mother_name_remove_profile_age_and_more'),
        ('student', '0011_remove_student_age_student_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('star', models.IntegerField(blank=True, default=0, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
