# Generated by Django 4.0.4 on 2022-07-24 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_alter_answer_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='star',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
