# Generated by Django 4.0.4 on 2022-07-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_answer_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
