# Generated by Django 4.0.4 on 2022-07-31 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='class_room',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='manager.classroom'),
            preserve_default=False,
        ),
    ]
