# Generated by Django 4.0.4 on 2022-06-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='head_teacher',
            field=models.ForeignKey(default='', limit_choices_to={'account_type': 'manager'}, on_delete=django.db.models.deletion.CASCADE, related_name='Holiday_profile', to='manager.profile'),
            preserve_default=False,
        ),
    ]
