# Generated by Django 4.0.4 on 2022-06-21 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_holiday_head_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_classroom', to='manager.classroom'),
        ),
    ]
