# Generated by Django 4.0.4 on 2022-07-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_rename_title_profile_mother_name_remove_profile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
    ]
