# Generated by Django 4.0.4 on 2022-07-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_question_question_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='approved',
        ),
    ]
