# Generated by Django 3.2.13 on 2022-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('employee', 'Employee'), ('manager', 'Manager')], default='manager', max_length=15),
        ),
    ]
