# Generated by Django 4.0.4 on 2022-05-20 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Subject_name',
            new_name='subject_name',
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(limit_choices_to={'account_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
