# Generated by Django 4.0.4 on 2022-05-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_mark_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='term_name',
            field=models.CharField(choices=[('Term1', '1'), ('Term2', '2')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
