# Generated by Django 4.0.4 on 2022-05-27 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_post_date_post_timee'),
        ('student', '0004_mark_term_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('pdf_from_teacher', models.FileField(blank=True, null=True, upload_to='pdf_teacher/')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_homeworkteacher', to='manager.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_homeworkteacher', to='student.subject')),
            ],
        ),
        migrations.CreateModel(
            name='HomeWorkStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('pdf_from_student', models.FileField(blank=True, null=True, upload_to='pdf_student/')),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework_homework', to='student.homeworkteacher')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_homework', to='student.student')),
            ],
        ),
    ]
