# Generated by Django 4.0.4 on 2022-05-27 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_post_date_post_timee'),
        ('student', '0005_homeworkteacher_homeworkstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkteacher',
            name='teacher',
            field=models.ForeignKey(default='', limit_choices_to={'user__account_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_homeworkteacher', to='manager.profile'),
            preserve_default=False,
        ),
    ]
