# Generated by Django 4.0.4 on 2022-05-27 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_homeworkteacher_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworkstudent',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_homework', to='student.homeworkteacher'),
        ),
    ]
