# Generated by Django 4.0.4 on 2022-05-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_post_date_post_timee'),
        ('student', '0007_alter_homeworkstudent_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylessons',
            name='teacher',
            field=models.ForeignKey(default='', limit_choices_to={'user__account_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_daelylessons', to='manager.profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailylessons',
            name='day',
            field=models.CharField(choices=[('sunday', '1'), ('monday', '2'), ('tuesday', '3'), ('wensday', '4'), ('thursday', '5')], max_length=30),
        ),
    ]
